server:
  port: 8081
  servlet:
    context-path: /api
  tomcat:
    max-connections: 1000
    min-spare-threads: 10
  connection-timeout: 2000
spring:
  profiles:
    active: dev
  jpa:
    database: MYSQl
    show-sql: true

